nelmio_api_doc:
    documentation:
        info:
            title: Loan Application API
            description: API for managing loan clients and loan applications.
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
            - ^/clients
            - ^/applications
