services:
  php:
    build: .
    container_name: loan_api_php
    volumes:
      - .:/var/www/app
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    container_name: loan_api_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: postgres:18-alpine
    container_name: loan_api_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql

volumes:
  database_data: